export const AUTOCOMPLETE_DATA_REQUEST = "AUTOCOMPLETE_DATA_REQUEST";
export const AUTOCOMPLETE_DATA_SUCCESS = "AUTOCOMPLETE_DATA_SUCCESS";
export const AUTOCOMPLETE_DATA_FAILURE = "AUTOCOMPLETE_DATA_FAILURE";

export const CURRENT_WEATHER_REQUEST = "CURRENT_WEATHER_REQUEST";
export const CURRENT_WEATHER_SUCCESS = "CURRENT_WEATHER_SUCCESS";
export const CURRENT_WEATHER_FAILURE = "CURRENT_WEATHER_FAILURE";